### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: kitti/testing/image_02/0001/000147.png'

### ISSUE THREAD

**Issue by Luo-Zhongwei** [ZwwWayne/mmMOT#18]
why is so odd,what wrong with kitti dataset?
![2020-04-27 18-26-00屏幕截图](https://user-images.githubusercontent.com/41502003/80362103-a14eac80-88b4-11ea-8b54-6a5fb71d9481.png)

runing command:
--------------------------------------------------------------------------------------
(mmmot) lzw@resplendent-star:~/resplendent_code/3d_tracking/mmMOT-master$ python -u eval_seq.py --config /home/lzw/resplendent_code/3d_tracking/mmMOT-master/experiments/pp_pv_40e_dualadd_subabs_C/config.yaml --load-path=/home/lzw/resplendent_code/3d_tracking/mmMOT-master/experiments/pp_pv_40e_dualadd_subabs_C/model/pp_pv_40e_dualadd_subabs_C.pth --result-path=/home/lzw/resplendent_code/3d_tracking/mmMOT-master/experiments/pp_pv_40e_dualadd_subabs_C/results  --result_sha=eval
Fusion Module C: split sigmoid weight gated point, image fusion
use Skip Pooling in appearance model
use avg in pointnet feat
Use minus_abs similarity with fusion module
End version V2 by avg
NewEndIndicator_v2(
  (conv0): Sequential(
    (0): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
    (1): GroupNorm(1, 512, eps=1e-05, affine=True)
    (2): ReLU(inplace=True)
  )
  (conv1): Sequential(
    (0): Conv1d(512, 512, kernel_size=(1,), stride=(1,))
    (1): GroupNorm(1, 512, eps=1e-05, affine=True)
    (2): ReLU(inplace=True)
    (3): Conv1d(512, 128, kernel_size=(1,), stride=(1,))
    (4): GroupNorm(1, 128, eps=1e-05, affine=True)
    (5): ReLU(inplace=True)
    (6): Conv1d(128, 1, kernel_size=(1,), stride=(1,))
    (7): Sigmoid()
  )
)
=> loading checkpoint '/home/lzw/resplendent_code/3d_tracking/mmMOT-master/experiments/pp_pv_40e_dualadd_subabs_C/model/pp_pv_40e_dualadd_subabs_C.pth'
Building dataset using dets file ./data/pp_train_dets.pkl
Detect [ 16258] cars in [3365/3975] images
Add [0] cars in [0/3975] images
Building dataset using dets file ./data/pp_val_dets.pkl
Detect [ 13170] cars in [3475/3945] images
Add [0] cars in [0/3945] images
[2020-04-27 18:20:40,697][eval_seq.py][line:  64][    INFO] args: Namespace(config='/home/lzw/resplendent_code/3d_tracking/mmMOT-master/experiments/pp_pv_40e_dualadd_subabs_C/config.yaml', evaluate=False, load_path='/home/lzw/resplendent_code/3d_tracking/mmMOT-master/experiments/pp_pv_40e_dualadd_subabs_C/model/pp_pv_40e_dualadd_subabs_C.pth', memory=False, recover=False, result_path='/home/lzw/resplendent_code/3d_tracking/mmMOT-master/experiments/pp_pv_40e_dualadd_subabs_C/results', result_sha='eval')
[2020-04-27 18:20:40,698][eval_seq.py][line:  65][    INFO] config: {'augmentation': {'input_size': 224, 'test_resize': 224},
 'batch_size': 1,
 'det_type': '3D',
 'dropblock': 0,
 'fixed_wd': True,
 'gt_det_ratio': 0,
 'loss': {'det_loss': 'bce',
          'det_ratio': 1.5,
          'link_loss': 'l2',
          'smooth_ratio': 0,
          'trans_last': True,
          'trans_ratio': 0.001},
 'lr_scheduler': {'base_lr': 0.0003,
                  'div_factor': 10.0,
                  'lr_max': 0.0006,
                  'max_iter': 134200,
                  'moms': [0.95, 0.85],
                  'optim': 'Adam',
                  'pct_start': 0.4,
                  'type': 'one_cycle'},
 'model': {'affinity_op': 'minus_abs',
           'appear_arch': 'vgg',
           'appear_fpn': False,
           'appear_len': 512,
           'appear_skippool': True,
           'end_arch': 'v2',
           'end_mode': 'avg',
           'neg_threshold': 0.2,
           'point_arch': 'v1',
           'point_len': 512,
           'score_arch': 'branch_cls',
           'score_fusion_arch': 'C',
           'softmax_mode': 'dual_add',
           'test_mode': 2},
 'momentum': 0.9,
 'print_freq': 100,
 'sample_max_len': 2,
 'save_path': '/home/lzw/resplendent_code/3d_tracking/mmMOT-master/experiments/pp_pv_40e_dualadd_subabs_C',
 'tracker_type': '3D',
 'train_det': './data/pp_train_dets.pkl',
 'train_fix_count': 0,
 'train_fix_iou': 1,
 'train_link': './data/train.txt',
 'train_root': './kitti_t_o/training',
 'train_source': './kitti_t_o/training/',
 'use_dropout': False,
 'use_frustum': False,
 'use_moving_average': False,
 'val_det': './data/pp_val_dets.pkl',
 'val_fix_count': 0,
 'val_fix_iou': 1,
 'val_freq': 3355,
 'val_link': './data/val.txt',
 'val_root': './kitti_t_o/training',
 'val_source': './kitti_t_o/training/',
 'weight_decay': 0.01,
 'without_reflectivity': True,
 'workers': 1}
[2020-04-27 18:20:40,699][eval_seq.py][line:  69][    INFO] Evaluation on traing set:
[2020-04-27 18:20:40,699][eval_seq.py][line:  89][    INFO] Test: [0/10]        Sequence ID: KITTI-0003
[2020-04-27 18:20:42,881][eval_seq.py][line: 160][    INFO] Test Frame: [0/143] Time 2.182(2.182)
[2020-04-27 18:20:59,636][eval_seq.py][line: 160][    INFO] Test Frame: [100/143]       Time 0.221(0.187)
Make directory: /home/lzw/resplendent_code/3d_tracking/mmMOT-master/experiments/pp_pv_40e_dualadd_subabs_C/results/eval/train
[2020-04-27 18:21:03,890][eval_seq.py][line:  89][    INFO] Test: [1/10]        Sequence ID: KITTI-0001
[2020-04-27 18:21:05,347][eval_seq.py][line: 160][    INFO] Test Frame: [0/422] Time 1.456(1.456)
[2020-04-27 18:21:40,783][eval_seq.py][line: 160][    INFO] Test Frame: [100/422]       Time 0.263(0.365)
Traceback (most recent call last):
  File "eval_seq.py", line 204, in <module>
    main()
  File "eval_seq.py", line 70, in main
    validate(train_dataset, tracking_module, args.result_sha, part='train')
  File "eval_seq.py", line 106, in validate
    seq_loader, tracking_module)
  File "eval_seq.py", line 144, in validate_seq
    for i, (input, det_info, dets, det_split) in enumerate(val_loader):
  File "/home/lzw/anaconda3/envs/mmmot/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/lzw/anaconda3/envs/mmmot/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/lzw/anaconda3/envs/mmmot/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lzw/anaconda3/envs/mmmot/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lzw/anaconda3/envs/mmmot/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lzw/anaconda3/envs/mmmot/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lzw/resplendent_code/3d_tracking/mmMOT-master/dataset/test_seq_dataset.py", line 139, in __getitem__
    return self._generate_img_lidar(idx)
  File "/home/lzw/resplendent_code/3d_tracking/mmMOT-master/dataset/test_seq_dataset.py", line 191, in _generate_img_lidar
    img = Image.open(path)
  File "/home/lzw/anaconda3/envs/mmmot/lib/python3.7/site-packages/PIL/Image.py", line 2770, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/lzw/new_add/dataset/kitti/testing/image_02/0001/000147.png'

(mmmot) lzw@resplendent-star:~/resplendent_code/3d_tracking/mmMOT-master$

**Comment by ZwwWayne** [comment]
I do not know about it, maybe you need to download the data again.

**Comment by Luo-Zhongwei** [comment]
> I do not know about it, maybe you need to download the data again.

thanks for you reply

**Comment by Luo-Zhongwei** [comment]
> I do not know about it, maybe you need to download the data again.

if you are free could plz  have  a  look at  you  mot kitti dataset？
testing/image_02/0001，this folder，to see how many  image in it
thanks very much

**Comment by ZwwWayne** [comment]
Ops, my data is from 0000 to 0146, I do not have 147. But I met no bug.

**Comment by llllliu1** [comment]
Hello, could you show me your catalog?When I run the same code as you, there is an error :.FileNotFoundError: [Errno 2] No such file or directory: './kitti_t_o/training/oxts/0000.txt' ,But I don't see oxts/ .... in the author's README
So I am confused about what the correct directory one looks like, I am looking forward to your reply.

**Comment by AdarshPan** [comment]
Hey I am getting the same error man!

Mind Helping me ??


here is the error code:
FileNotFoundError: [Errno 2] No such file or directory: 'media/ransome.png'

Just Dunno whats going on
