### ISSUE TITLE
velodyne_reduced path issue

### ISSUE THREAD

**Issue by FrankCAN** [ZwwWayne/mmMOT#27]
Hi, thanks for sharing your great work, but I got a problem when I use rrc detector to train the model, the error is as below:

Det ratio 1.5
Only calculate the last transform with weight 0.001
Building dataset using dets file ./data/RRC_Detections_mat/train
Detect [0] in  [0/3999] images with detections
Add [0] cars in [0/3999] images
Building dataset using dets file ./data/RRC_Detections_mat/train
Detect [0] in  [0/3999] images with detections
Add [0] cars in [0/3999] images
Building dataset using dets file ./data/RRC_Detections_mat/train
Detect [0] in  [0/3864] images with detections
Add [0] cars in [0/3864] images
Traceback (most recent call last):
  File "/home/chencan/Phd_Projects/01_tracking/mmMOT/main.py", line 275, in <module>
    main()
  File "/home/chencan/Phd_Projects/01_tracking/mmMOT/main.py", line 89, in main
    last_iter=last_iter)
  File "/home/chencan/Phd_Projects/01_tracking/mmMOT/utils/train_util.py", line 116, in __init__
    self.indices = self.gen_new_list()
  File "/home/chencan/Phd_Projects/01_tracking/mmMOT/utils/train_util.py", line 133, in gen_new_list
    num_repeat = (all_size - 1) // origin_indices.shape[0] + 1
ZeroDivisionError: integer division or modulo by zero

I checked the code that the problem comes from the unavailable path "point_path = f'{root_dir}/velodyne_reduced/{seq_id}-{frame_id}.bin', which leads to empty detect results."

So I just wonder if I missed some important steps for data preprocessing or it is a bug.

Many thanks for your help.

**Comment by ZwwWayne** [comment]
Hi @FrankCAN ,
Could you check which frame is missing? For example, what is the sequence ID and frame ID?
It seems that no detection boxes are loaded during training.

**Comment by FrankCAN** [comment]
Hi, thanks for your response. I finally managed to train your rrc version model, and also submitted it to the server.
The accuracy results are quite similar to yours on the paper, but the big issue is the ID-switch result and Fragment result. What I got are as below:

ID-switches                                                                  400
Fragmentations                                                               859

But your results are 
ID-switches                                                                  284
Fragmentations                                                               753


I don't understand why all other metrics are quite similar, or even the same for some metrics, but only ID-s and Frag are quite different. And also how to train your model and achieve similar results? 

Many thanks for your help.
