### ISSUE TITLE
Prec  Rec  MOTA are   all  zero and  got errors

### ISSUE THREAD

**Issue by Ri-Bai** [ZwwWayne/mmMOT#45]

**Comment by Ri-Bai** [comment]
Processing Result for KITTI Tracking Benchmark
The uploaded results could not be evaluated. Check for format errors.
[2021-09-26 09:49:26,062][eval_seq.py][line: 127][    INFO] * Prec: 0.000	Rec: 0.000	MOTA: 0.000	MOTP: 0.000	total_num=10.0
Traceback (most recent call last):
  File "/home/vci-1/BR/fusion/mmMOT-master/eval_seq.py", line 208, in <module>
    main()
  File "/home/vci-1/BR/fusion/mmMOT-master/eval_seq.py", line 70, in main
    validate(train_dataset, tracking_module, args.result_sha, part='train')
  File "/home/vci-1/BR/fusion/mmMOT-master/eval_seq.py", line 128, in validate
    MOTA, MOTP, recall, prec, F1, fp, fn, id_switches = evaluate(step, args.result_path, part=part)
TypeError: cannot unpack non-iterable bool object

Process finished with exit code 1

**Comment by Ri-Bai** [comment]
I found the code follow:
"aligned_ids, aligned_dets, frame_start = tracking_module.predict(input[0], det_info, dets, det_split)"

 in  the eval_seq.py  in 157 line
  were not be used(aligned_ids,aligned_dets, frame_start  are not be used in the class "validate_seq 

and the class"vaildate_seq" return  0 0 0 0 "),I want to know what happened in this code .are them all right and needn't to change anything?
