### ISSUE TITLE
Failed to use kitti_devkit

### ISSUE THREAD

**Issue by simaker** [ZwwWayne/mmMOT#7]
I want to evaluate Data with the kitti_dev kit but i received this error: 

python3 evaluate_tracking.py /home/sim/mmMOT eval
Processing Result for KITTI Tracking Benchmark
Traceback (most recent call last):
  File "evaluate_tracking.py", line 980, in <module>
    success = evaluate(result_sha, root, mail)
  File "evaluate_tracking.py", line 914, in evaluate
    e = trackingEvaluation(t_sha=result_sha, root=root, part=part, mail=mail,cls=c)
  File "evaluate_tracking.py", line 135, in __init__
    self.t_path            = os.path.join(root, t_sha, part)
  File "/usr/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'Mail'

**Comment by ZwwWayne** [comment]
You might need to check your argument from this [line](https://github.com/ZwwWayne/mmMOT/blob/master/kitti_devkit/evaluate_tracking.py#L963).

**Comment by simaker** [comment]
Thank you for your answer. I solved the problem.
